blank_issues_enabled: false
contact_links:
  - name: 💬 EF-Derby Community Discussions & Q&A
    url: https://github.com/ef-derby/ef-derby/discussions
    about: Ask questions, share ideas, and connect with other Derby players.
